import { IAgenda } from "../models/agenda";

export const agenda: IAgenda[] = [
  {
    title: 'Registration and T-shirt collection',
    speakerName: '',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/registration.png',
    startTime: '9:00 AM',
    endTime: '10:00 AM',
    description: '',
  },
  {
    title: 'Welcome',
    speakerName: '',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/award.png',
    startTime: '10:00 AM',
    endTime: '10:30 AM',
    description: '',
  },
  {
    title: 'Beyond ReAct: Building Reliable AI Agents with LangGraph',
    speakerName: 'Dhananjay Kumar',
    speakerPosition: 'Founder nomadcoder | AI-India',
    speakerImage: 'assets/images/speakers/dj.jpeg',
    startTime: '10:30 AM',
    endTime: '11:00 AM',
    description: '',
  },
  {
    title: 'Self-improving agent architectures',
    speakerName: 'Priyanka Kore',
    speakerPosition: 'Lead @Adesso India',
    speakerImage: 'assets/images/speakers/priyanka.jpeg',
    startTime: '11:00 AM',
    endTime: '11:30 AM',
    description: '',
  },
  {
    title: "We Can't Improve What we Can't Measure: Evals, Harnesses, and Silent Failure in Production Agents",
    speakerName: 'Jeevan D C',
    speakerPosition: 'Engineering Manager @Entain',
    speakerImage: 'assets/images/speakers/jeevan.jpeg',
    startTime: '11:30 AM',
    endTime: '12:00 PM',
    description: '',
  },
  {
    title: 'Your evals are lying to you',
    speakerName: 'Varun S',
    speakerPosition: '',
    speakerImage: '',
    startTime: '12:00 PM',
    endTime: '12:30 PM',
    description: '',
  },
  {
    title: 'TBD',
    speakerName: 'ShivPrasad Koirala',
    speakerPosition: 'Founder @Questpond',
    speakerImage: 'assets/images/speakers/shivprasad.jpeg',
    startTime: '12:30 PM',
    endTime: '1:00 PM',
    description: '',
  },
  {
    title: 'Lunch',
    speakerName: '',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/lunch-break.png',
    startTime: '1:00 PM',
    endTime: '2:00 PM',
    description: '',
  },
  {
    title: 'A Guardrail Blueprint for Production AI Agents',
    speakerName: 'Laxminarayan Chandrashekar',
    speakerPosition: 'Technical Lead and Architect @Siemens',
    speakerImage: 'assets/images/speakers/laxmin.png',
    startTime: '2:00 PM',
    endTime: '2:30 PM',
    description: '',
  },
  {
    title: 'From Commit to Production: Building AI-Ready CI/CD Pipelines with Harness',
    speakerName: 'Arumulla Yaswanth Reddy',
    speakerPosition: 'Software Engineer @Arealis Networks',
    speakerImage: 'assets/images/speakers/arumulla.png',
    startTime: '2:30 PM',
    endTime: '3:00 PM',
    description: '',
  },
  {
    title: 'Running Offline AI on Mobile Devices',
    speakerName: 'Infant Mystica',
    speakerPosition: 'Software Developer @TranslateLive',
    speakerImage: 'assets/images/speakers/mysteica.jpeg',
    startTime: '3:00 PM',
    endTime: '3:30 PM',
    description: '',
  },
  {
    title: 'Voice Agents: Ready for Production or Just a Great Demo?',
    speakerName: 'Manoranjan Rajguru',
    speakerPosition: '',
    speakerImage: '',
    startTime: '3:30 PM',
    endTime: '4:00 PM',
    description: '',
  },
  {
    title: 'Tea break',
    speakerName: '',
    speakerPosition: '',
    speakerImage: 'assets/images/agenda/tea-cup.png',
    startTime: '4:00 PM',
    endTime: '4:30 PM',
    description: '',
  },
  {
    title: 'A brief intro to Inference Engineering for Software Engineers',
    speakerName: 'Chinmay Naik',
    speakerPosition: 'Founder @One2N',
    speakerImage: 'assets/images/speakers/chinmay.jpg',
    startTime: '4:30 PM',
    endTime: '5:00 PM',
    description: '',
  },
  {
    title: 'Engineering a Model Router for Cost, Latency & Quality',
    speakerName: 'Sunny Sharma',
    speakerPosition: '',
    speakerImage: '',
    startTime: '5:00 PM',
    endTime: '5:30 PM',
    description: '',
  },
  {
    title: 'MCP at Scale: Going Serverless',
    speakerName: 'Sumit Parakh',
    speakerPosition: 'Principal Software Engineer @Perforce Software',
    speakerImage: 'assets/images/speakers/sumit.jpeg',
    startTime: '5:30 PM',
    endTime: '6:00 PM',
    description: '',
  },
  {
    title: 'MCP is Alive and How to Use it the Best Way',
    speakerName: 'Nidhi Singh',
    speakerPosition: '',
    speakerImage: '',
    startTime: '6:00 PM',
    endTime: '6:30 PM',
    description: '',
  },
];
